import type { FormularDefinition } from './types';

export const FORMULARE_KATALOG: FormularDefinition[] = [
  {
    formularId: 'F-01',
    name: 'Wareneingang-Check',
    beschreibung: 'Eingangskontrolle für Lieferungen – Dokumentation von Lieferant, Ware, Zustand und Freigabe.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'uhrzeit', label: 'Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'lieferant', label: 'Lieferant', typ: 'text', pflichtfeld: true, platzhalter: 'Name des Lieferanten', breite: 'halb', gruppe: 'Lieferung' },
      { id: 'lieferschein_nr', label: 'Lieferschein-Nr.', typ: 'text', platzhalter: 'LS-12345', breite: 'halb', gruppe: 'Lieferung' },
      { id: 'fahrzeug_kennzeichen', label: 'Fahrzeug-Kennzeichen', typ: 'text', platzhalter: 'z. B. MU-AB 1234', breite: 'halb', gruppe: 'Lieferung' },
      { id: 'fahrer_name', label: 'Fahrername', typ: 'text', breite: 'halb', gruppe: 'Lieferung' },
      { id: 'waren_beschreibung', label: 'Warenbezeichnung / Beschreibung', typ: 'textarea', pflichtfeld: true, platzhalter: 'Art und Menge der angelieferten Ware', gruppe: 'Warenkontrolle' },
      { id: 'menge_soll', label: 'Menge SOLL', typ: 'number', breite: 'halb', gruppe: 'Warenkontrolle' },
      { id: 'menge_ist', label: 'Menge IST', typ: 'number', breite: 'halb', gruppe: 'Warenkontrolle' },
      { id: 'zustand', label: 'Zustand der Ware', typ: 'select', optionen: ['Ordnungsgemäß', 'Beschädigt', 'Teilbeschädigt', 'Unklar'], pflichtfeld: true, gruppe: 'Warenkontrolle' },
      { id: 'auffaelligkeiten', label: 'Auffälligkeiten', typ: 'textarea', platzhalter: 'Beschädigungen, Fehlmengen, Unregelmäßigkeiten…', gruppe: 'Warenkontrolle' },
      { id: 'pruefperson', label: 'Prüfperson', typ: 'text', pflichtfeld: true, platzhalter: 'Name des prüfenden Mitarbeiters', breite: 'halb', gruppe: 'Freigabe' },
      { id: 'freigabe', label: 'Freigabe', typ: 'select', optionen: ['Freigegeben', 'Abgelehnt', 'Klärungsbedarf'], pflichtfeld: true, breite: 'halb', gruppe: 'Freigabe' },
      { id: 'bemerkungen', label: 'Bemerkungen', typ: 'textarea', gruppe: 'Freigabe' },
    ],
  },
  {
    formularId: 'F-02',
    name: 'Schichtübergabe-Karte',
    beschreibung: 'Dokumentation der Schichtübergabe zwischen Sicherheitsmitarbeitern.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Schichtdaten' },
      { id: 'bereich', label: 'Bereich / Objekt', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Schichtdaten' },
      { id: 'schicht_von', label: 'Schicht von', typ: 'time', pflichtfeld: true, breite: 'halb', gruppe: 'Schichtdaten' },
      { id: 'schicht_bis', label: 'Schicht bis', typ: 'time', pflichtfeld: true, breite: 'halb', gruppe: 'Schichtdaten' },
      { id: 'uebergebender', label: 'Übergebender Mitarbeiter', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Personal' },
      { id: 'uebernehmender', label: 'Übernehmender Mitarbeiter', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Personal' },
      { id: 'schluessel_uebergeben', label: 'Schlüssel übergeben', typ: 'select', optionen: ['Ja', 'Nein', 'Nicht zutreffend'], breite: 'halb', gruppe: 'Übergabe' },
      { id: 'alarme_ausgeloest', label: 'Alarm ausgelöst in der Schicht', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Übergabe' },
      { id: 'alarme_beschreibung', label: 'Alarm – Beschreibung', typ: 'textarea', platzhalter: 'Art, Ursache und Maßnahmen bei Alarm', gruppe: 'Übergabe' },
      { id: 'vorfaelle', label: 'Vorfälle in der Schicht', typ: 'textarea', platzhalter: 'Alle sicherheitsrelevanten Ereignisse…', gruppe: 'Bericht' },
      { id: 'offene_aufgaben', label: 'Offene Aufgaben / Aufträge', typ: 'textarea', platzhalter: 'Was muss in der Folgeschicht erledigt werden?', gruppe: 'Bericht' },
      { id: 'besondere_vorkommnisse', label: 'Besondere Vorkommnisse', typ: 'textarea', gruppe: 'Bericht' },
      { id: 'bemerkungen', label: 'Sonstige Bemerkungen', typ: 'textarea', gruppe: 'Bericht' },
    ],
  },
  {
    formularId: 'F-03',
    name: 'Auf- & Verschlussliste',
    beschreibung: 'Protokollierung von Aufschluss, Begehungen und Verschluss eines Bereichs oder Objekts.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'bereich', label: 'Bereich / Objekt', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'verantwortlicher', label: 'Verantwortlicher', typ: 'text', pflichtfeld: true, gruppe: 'Grunddaten' },
      { id: 'aufschluss_uhrzeit', label: 'Aufschluss – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Aufschluss' },
      { id: 'aufschluss_person', label: 'Aufschluss – Person', typ: 'text', breite: 'halb', gruppe: 'Aufschluss' },
      { id: 'aufschluss_befund', label: 'Aufschluss – Befund / Besonderheiten', typ: 'textarea', gruppe: 'Aufschluss' },
      { id: 'begehung_1_zeit', label: 'Begehung 1 – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Begehungen' },
      { id: 'begehung_1_person', label: 'Begehung 1 – Person', typ: 'text', breite: 'halb', gruppe: 'Begehungen' },
      { id: 'begehung_1_befund', label: 'Begehung 1 – Befund', typ: 'textarea', gruppe: 'Begehungen' },
      { id: 'begehung_2_zeit', label: 'Begehung 2 – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Begehungen' },
      { id: 'begehung_2_person', label: 'Begehung 2 – Person', typ: 'text', breite: 'halb', gruppe: 'Begehungen' },
      { id: 'begehung_2_befund', label: 'Begehung 2 – Befund', typ: 'textarea', gruppe: 'Begehungen' },
      { id: 'verschluss_uhrzeit', label: 'Verschluss – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Verschluss' },
      { id: 'verschluss_person', label: 'Verschluss – Person', typ: 'text', breite: 'halb', gruppe: 'Verschluss' },
      { id: 'verschluss_befund', label: 'Verschluss – Befund / Besonderheiten', typ: 'textarea', gruppe: 'Verschluss' },
      { id: 'auffaelligkeiten', label: 'Auffälligkeiten gesamt', typ: 'textarea', gruppe: 'Abschluss' },
      { id: 'bemerkungen', label: 'Bemerkungen', typ: 'textarea', gruppe: 'Abschluss' },
    ],
  },
  {
    formularId: 'F-04',
    name: 'Fremdfirmen- & Besucherbriefing',
    beschreibung: 'Erfassung und Sicherheitsunterweisung von externen Personen und Besuchern.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Besuchsdaten' },
      { id: 'uhrzeit_einlass', label: 'Einlass – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Besuchsdaten' },
      { id: 'besucher_name', label: 'Name der Person', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Personendaten' },
      { id: 'besucher_unternehmen', label: 'Unternehmen / Organisation', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Personendaten' },
      { id: 'besuch_bei', label: 'Besuch bei (Ansprechpartner intern)', typ: 'text', breite: 'halb', gruppe: 'Personendaten' },
      { id: 'besuchsgrund', label: 'Grund des Besuchs / Auftrag', typ: 'textarea', pflichtfeld: true, gruppe: 'Personendaten' },
      { id: 'ausweis_art', label: 'Ausweisart', typ: 'select', optionen: ['Personalausweis', 'Reisepass', 'Führerschein', 'Firmenausweis', 'Sonstiges'], breite: 'halb', gruppe: 'Identifikation' },
      { id: 'ausweis_nr', label: 'Ausweis-Nr.', typ: 'text', breite: 'halb', gruppe: 'Identifikation' },
      { id: 'fahrzeug_kennzeichen', label: 'Fahrzeug-Kennzeichen', typ: 'text', breite: 'halb', gruppe: 'Identifikation' },
      { id: 'zutritt_bereich', label: 'Zugelassener Bereich', typ: 'text', platzhalter: 'z. B. Lager, Büro EG, Produktionshalle', breite: 'halb', gruppe: 'Identifikation' },
      { id: 'sicherheitsunterweisung', label: 'Sicherheitsunterweisung erfolgt', typ: 'select', optionen: ['Ja', 'Nein'], pflichtfeld: true, breite: 'halb', gruppe: 'Unterweisung' },
      { id: 'hausordnung', label: 'Hausordnung bekanntgemacht', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Unterweisung' },
      { id: 'nda_unterzeichnet', label: 'Geheimhaltungsvereinbarung', typ: 'select', optionen: ['Ja', 'Nein', 'Nicht erforderlich'], breite: 'halb', gruppe: 'Unterweisung' },
      { id: 'begleitperson', label: 'Begleitperson intern', typ: 'text', breite: 'halb', gruppe: 'Unterweisung' },
      { id: 'uhrzeit_auslass', label: 'Auslass – Uhrzeit', typ: 'time', breite: 'halb', gruppe: 'Abschluss' },
      { id: 'empfang_mitarbeiter', label: 'Empfang – Mitarbeiter', typ: 'text', breite: 'halb', gruppe: 'Abschluss' },
      { id: 'bemerkungen', label: 'Bemerkungen', typ: 'textarea', gruppe: 'Abschluss' },
    ],
  },
  {
    formularId: 'F-05',
    name: 'Notfallkarte M5',
    beschreibung: 'Zentrale Notfallkarte mit Notrufnummern, Sammelplätzen und Verantwortlichen.',
    felder: [
      { id: 'standort', label: 'Standort / Objekt', typ: 'text', pflichtfeld: true, gruppe: 'Grunddaten' },
      { id: 'letzte_aktualisierung', label: 'Letzte Aktualisierung', typ: 'date', breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'notruf_feuerwehr', label: 'Feuerwehr', typ: 'text', platzhalter: '112', breite: 'halb', gruppe: 'Notrufnummern' },
      { id: 'notruf_polizei', label: 'Polizei', typ: 'text', platzhalter: '110', breite: 'halb', gruppe: 'Notrufnummern' },
      { id: 'notruf_rettungsdienst', label: 'Rettungsdienst', typ: 'text', platzhalter: '112', breite: 'halb', gruppe: 'Notrufnummern' },
      { id: 'notruf_giftnotruf', label: 'Giftnotruf', typ: 'text', platzhalter: '030 19240', breite: 'halb', gruppe: 'Notrufnummern' },
      { id: 'kontakt_betriebsarzt', label: 'Betriebsarzt', typ: 'text', breite: 'halb', gruppe: 'Interne Notfallkontakte' },
      { id: 'kontakt_werkschutz', label: 'Werkschutz / Sicherheitszentrale', typ: 'text', breite: 'halb', gruppe: 'Interne Notfallkontakte' },
      { id: 'kontakt_betriebsleitung', label: 'Betriebsleitung (Notfall)', typ: 'text', breite: 'halb', gruppe: 'Interne Notfallkontakte' },
      { id: 'kontakt_sonstiges', label: 'Sonstiger Notfallkontakt', typ: 'text', breite: 'halb', gruppe: 'Interne Notfallkontakte' },
      { id: 'sammelplatz_1', label: 'Sammelplatz 1 (Hauptsammelplatz)', typ: 'text', pflichtfeld: true, gruppe: 'Evakuierung' },
      { id: 'sammelplatz_2', label: 'Sammelplatz 2 (Ausweichsammelplatz)', typ: 'text', gruppe: 'Evakuierung' },
      { id: 'evakuierungsverantwortlicher_name', label: 'Evakuierungsverantwortlicher – Name', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Evakuierung' },
      { id: 'evakuierungsverantwortlicher_tel', label: 'Evakuierungsverantwortlicher – Tel.', typ: 'text', breite: 'halb', gruppe: 'Evakuierung' },
      { id: 'ersthelfer_1_name', label: 'Ersthelfer 1 – Name', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'ersthelfer_1_tel', label: 'Ersthelfer 1 – Tel.', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'ersthelfer_2_name', label: 'Ersthelfer 2 – Name', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'ersthelfer_2_tel', label: 'Ersthelfer 2 – Tel.', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'brandschutzbeauftragter_name', label: 'Brandschutzbeauftragter – Name', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'brandschutzbeauftragter_tel', label: 'Brandschutzbeauftragter – Tel.', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'sicherheitsbeauftragter_name', label: 'Sicherheitsbeauftragter – Name', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'sicherheitsbeauftragter_tel', label: 'Sicherheitsbeauftragter – Tel.', typ: 'text', breite: 'halb', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'aed_standort', label: 'AED-Standort (Defibrillator)', typ: 'text', gruppe: 'Ersthelfer & Beauftragte' },
      { id: 'besondere_gefahren', label: 'Besondere Gefahren am Standort', typ: 'textarea', platzhalter: 'Gefahrstoffe, Hochspannung, besondere Risiken…', gruppe: 'Gefahren' },
    ],
  },
  {
    formularId: 'F-06',
    name: 'Schlüssel- & Spezialmittelverzeichnis',
    beschreibung: 'Ausgabe und Rückgabe von Schlüsseln, Chipkarten und Zugangsmitteln.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'objekt_bezeichnung', label: 'Objekt / Standort', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Grunddaten' },
      { id: 'verantwortlicher', label: 'Verantwortlicher (Schlüsselverwalter)', typ: 'text', pflichtfeld: true, gruppe: 'Grunddaten' },
      { id: 'schluessel_bezeichnung', label: 'Schlüsselbezeichnung', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Schlüsseldaten' },
      { id: 'schluessel_nr', label: 'Schlüssel-Nr. / Kennung', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Schlüsseldaten' },
      { id: 'schluessel_typ', label: 'Schlüsselart', typ: 'select', optionen: ['Schlüssel', 'Chipkarte', 'Code', 'Fernbedienung', 'Sonstiges'], pflichtfeld: true, breite: 'halb', gruppe: 'Schlüsseldaten' },
      { id: 'anzahl_kopien', label: 'Anzahl Kopien', typ: 'number', breite: 'halb', gruppe: 'Schlüsseldaten' },
      { id: 'zugelassene_bereiche', label: 'Zugelassene Bereiche / Türen', typ: 'textarea', gruppe: 'Schlüsseldaten' },
      { id: 'ausgabe_an', label: 'Ausgabe an (Name)', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Ausgabe' },
      { id: 'funktion_empfaenger', label: 'Funktion / Abteilung', typ: 'text', breite: 'halb', gruppe: 'Ausgabe' },
      { id: 'ausgabe_datum', label: 'Ausgabedatum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Ausgabe' },
      { id: 'ausgabe_person', label: 'Ausgabe durch', typ: 'text', breite: 'halb', gruppe: 'Ausgabe' },
      { id: 'rueckgabe_datum', label: 'Rückgabedatum', typ: 'date', breite: 'halb', gruppe: 'Rückgabe' },
      { id: 'rueckgabe_person', label: 'Rückgabe entgegengenommen durch', typ: 'text', breite: 'halb', gruppe: 'Rückgabe' },
      { id: 'zustand_rueckgabe', label: 'Zustand bei Rückgabe', typ: 'select', optionen: ['Einwandfrei', 'Beschädigt', 'Verloren / Nicht zurückgegeben'], gruppe: 'Rückgabe' },
      { id: 'bemerkungen', label: 'Bemerkungen', typ: 'textarea', gruppe: 'Rückgabe' },
    ],
  },
  {
    formularId: 'F-07',
    name: 'Erstmeldung Störfall',
    beschreibung: 'Erste strukturierte Dokumentation eines sicherheitsrelevanten Vorfalls.',
    felder: [
      { id: 'datum', label: 'Datum', typ: 'date', pflichtfeld: true, breite: 'halb', gruppe: 'Meldung' },
      { id: 'uhrzeit', label: 'Uhrzeit der Meldung', typ: 'time', pflichtfeld: true, breite: 'halb', gruppe: 'Meldung' },
      { id: 'meldender_name', label: 'Meldender – Name', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Meldung' },
      { id: 'meldender_funktion', label: 'Meldender – Funktion', typ: 'text', breite: 'halb', gruppe: 'Meldung' },
      { id: 'meldender_tel', label: 'Meldender – Telefon', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Meldung' },
      { id: 'ort_des_vorfalls', label: 'Ort des Vorfalls', typ: 'text', pflichtfeld: true, breite: 'halb', gruppe: 'Vorfall' },
      { id: 'art_des_vorfalls', label: 'Art des Vorfalls', typ: 'select', optionen: ['Einbruch', 'Diebstahl', 'Körperverletzung', 'Bedrohung', 'Vandalismus', 'Sachschaden', 'Brand', 'Wasserschaden', 'Arbeitsunfall', 'Cyberangriff', 'Sonstiges'], pflichtfeld: true, gruppe: 'Vorfall' },
      { id: 'tatzeit_von', label: 'Tatzeit / Vorfall von', typ: 'time', breite: 'halb', gruppe: 'Vorfall' },
      { id: 'tatzeit_bis', label: 'Tatzeit / Vorfall bis', typ: 'time', breite: 'halb', gruppe: 'Vorfall' },
      { id: 'kurzbeschreibung', label: 'Kurzbeschreibung des Vorfalls', typ: 'textarea', pflichtfeld: true, platzhalter: 'Was ist passiert? Wer war beteiligt? Womit?', gruppe: 'Vorfall' },
      { id: 'betroffene_personen_anzahl', label: 'Betroffene Personen (Anzahl)', typ: 'number', breite: 'halb', gruppe: 'Personenschäden' },
      { id: 'verletzte_personen', label: 'Verletzte Personen', typ: 'select', optionen: ['Ja', 'Nein', 'Unbekannt'], breite: 'halb', gruppe: 'Personenschäden' },
      { id: 'sofortmassnahmen', label: 'Eingeleitete Sofortmaßnahmen', typ: 'textarea', platzhalter: 'Welche Maßnahmen wurden unmittelbar ergriffen?', gruppe: 'Maßnahmen' },
      { id: 'benachrichtigt_polizei', label: 'Polizei benachrichtigt', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Benachrichtigungen' },
      { id: 'polizei_aktenzeichen', label: 'Polizei – Aktenzeichen', typ: 'text', breite: 'halb', gruppe: 'Benachrichtigungen' },
      { id: 'benachrichtigt_feuerwehr', label: 'Feuerwehr benachrichtigt', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Benachrichtigungen' },
      { id: 'benachrichtigt_betriebsleitung', label: 'Betriebsleitung benachrichtigt', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Benachrichtigungen' },
      { id: 'benachrichtigt_sonstiges', label: 'Sonstige Benachrichtigungen', typ: 'text', gruppe: 'Benachrichtigungen' },
      { id: 'zeugen', label: 'Zeugen (Namen / Kontakt)', typ: 'textarea', gruppe: 'Beweise & Schaden' },
      { id: 'schaetzung_schaden', label: 'Schadensschätzung', typ: 'text', platzhalter: 'z. B. ca. 5.000 €', breite: 'halb', gruppe: 'Beweise & Schaden' },
      { id: 'fotos_gemacht', label: 'Fotos / Dokumentation erstellt', typ: 'select', optionen: ['Ja', 'Nein'], breite: 'halb', gruppe: 'Beweise & Schaden' },
      { id: 'sichergestellte_beweise', label: 'Sichergestellte Beweise / Aufzeichnungen', typ: 'textarea', gruppe: 'Beweise & Schaden' },
      { id: 'bemerkungen', label: 'Sonstige Bemerkungen', typ: 'textarea', gruppe: 'Abschluss' },
    ],
  },
];

export function getFormularDefinition(formularId: string): FormularDefinition | undefined {
  return FORMULARE_KATALOG.find((f) => f.formularId === formularId);
}
