import type { ChecklisteAnlage, ChecklisteAnlageMeta } from './types';

export const CHECKLISTEN_KATALOG: ChecklisteAnlage[] = [
  {
    anlageId: 'A-01',
    name: 'Management-Selbstbewertung LPM-System',
    beschreibung: 'Bewertung des Loss Prevention Management Systems auf strategischer Ebene.',
    fragen: [
      { frageId: 'A-01-1-1', abschnitt: '1. Strategische Verankerung', frageText: 'Ist Loss Prevention als eigenständige Funktion in der Unternehmensstruktur verankert?' },
      { frageId: 'A-01-1-2', abschnitt: '1. Strategische Verankerung', frageText: 'Gibt es eine schriftlich fixierte LPM-Strategie mit messbaren Zielen?' },
      { frageId: 'A-01-1-3', abschnitt: '1. Strategische Verankerung', frageText: 'Berichtet der LP-Verantwortliche direkt an die Geschäftsführung oder ein Steuerungsgremium?' },
      { frageId: 'A-01-2-1', abschnitt: '2. Ressourcen', frageText: 'Sind ausreichend personelle und finanzielle Ressourcen für LP-Maßnahmen eingeplant?' },
      { frageId: 'A-01-2-2', abschnitt: '2. Ressourcen', frageText: 'Wird ein LP-Budget auf Basis von Risikobewertungen festgelegt und überwacht?' },
      { frageId: 'A-01-2-3', abschnitt: '2. Ressourcen', frageText: 'Werden LP-relevante KPIs (Schwundquote, Vorfallrate) regelmäßig erhoben und berichtet?' },
      { frageId: 'A-01-3-1', abschnitt: '3. Prozesse und Dokumentation', frageText: 'Sind alle LP-Kernprozesse dokumentiert und für zuständige Mitarbeiter zugänglich?' },
      { frageId: 'A-01-3-2', abschnitt: '3. Prozesse und Dokumentation', frageText: 'Werden LP-Prozesse mindestens jährlich auf Aktualität geprüft und angepasst?' },
      { frageId: 'A-01-4-1', abschnitt: '4. Integritätskultur', frageText: 'Wird eine Integritätskultur aktiv durch das Management vorgelebt und kommuniziert?' },
      { frageId: 'A-01-4-2', abschnitt: '4. Integritätskultur', frageText: 'Existiert ein vertraulicher Meldekanal für LP-relevante Verdachtsfälle (Hinweisgebersystem)?' },
      { frageId: 'A-01-4-3', abschnitt: '4. Integritätskultur', frageText: 'Werden Hinweisgeber vor Repressalien geschützt und werden Meldungen ernsthaft verfolgt?' },
    ],
  },
  {
    anlageId: 'A-02',
    name: 'Personalintegrität und Auswahlprozesse',
    beschreibung: 'Prüfung der Maßnahmen zur Sicherstellung der Personalintegrität bei Einstellung und im laufenden Betrieb.',
    fragen: [
      { frageId: 'A-02-1-1', abschnitt: '1. Hintergrundüberprüfung', frageText: 'Werden vor der Einstellung Hintergrundüberprüfungen (Referenzen, Leumund) standardisiert durchgeführt?' },
      { frageId: 'A-02-1-2', abschnitt: '1. Hintergrundüberprüfung', frageText: 'Sind die Überprüfungsstandards je nach Risikostufe der Position abgestuft?' },
      { frageId: 'A-02-1-3', abschnitt: '1. Hintergrundüberprüfung', frageText: 'Werden Lücken im Lebenslauf systematisch hinterfragt und dokumentiert?' },
      { frageId: 'A-02-2-1', abschnitt: '2. Einstellungsprozess', frageText: 'Gibt es strukturierte Integritätsinterviews als Bestandteil des Auswahlverfahrens?' },
      { frageId: 'A-02-2-2', abschnitt: '2. Einstellungsprozess', frageText: 'Werden Bewerber über LP-Richtlinien und Konsequenzen von Fehlverhalten informiert?' },
      { frageId: 'A-02-2-3', abschnitt: '2. Einstellungsprozess', frageText: 'Ist der LP-Bereich in die Freigabe von risikorelevanten Positionen eingebunden?' },
      { frageId: 'A-02-3-1', abschnitt: '3. Laufende Prüfung', frageText: 'Werden Mitarbeiter in risikorelevanten Positionen regelmäßig re-evaluiert?' },
      { frageId: 'A-02-3-2', abschnitt: '3. Laufende Prüfung', frageText: 'Gibt es ein System zur Erfassung und Bewertung von Verhaltensauffälligkeiten?' },
      { frageId: 'A-02-3-3', abschnitt: '3. Laufende Prüfung', frageText: 'Werden bei Positionswechseln mit erhöhten LP-Risiken erneute Überprüfungen durchgeführt?' },
    ],
  },
  {
    anlageId: 'A-03',
    name: 'Einarbeitung, Schulung und Sensibilisierung',
    beschreibung: 'Bewertung der LP-bezogenen Schulungs- und Einarbeitungsmaßnahmen.',
    fragen: [
      { frageId: 'A-03-1-1', abschnitt: '1. Onboarding', frageText: 'Enthält das Onboarding-Programm einen verpflichtenden LP-Schulungsblock?' },
      { frageId: 'A-03-1-2', abschnitt: '1. Onboarding', frageText: 'Werden neue Mitarbeiter über das Insider-Risiko und typische Tatmuster aufgeklärt?' },
      { frageId: 'A-03-1-3', abschnitt: '1. Onboarding', frageText: 'Bestätigen Mitarbeiter schriftlich, LP-Richtlinien und Verhaltenskodex erhalten und verstanden zu haben?' },
      { frageId: 'A-03-2-1', abschnitt: '2. Laufende Schulungen', frageText: 'Finden regelmäßige (mind. jährliche) LP-Auffrischungsschulungen für alle Mitarbeiter statt?' },
      { frageId: 'A-03-2-2', abschnitt: '2. Laufende Schulungen', frageText: 'Werden Führungskräfte gesondert zu LP-Themen (Erkennung, Führungsverantwortung) geschult?' },
      { frageId: 'A-03-2-3', abschnitt: '2. Laufende Schulungen', frageText: 'Wird der Schulungserfolg nachgehalten (Teilnahmelisten, Wissenstests)?' },
      { frageId: 'A-03-3-1', abschnitt: '3. Situative Sensibilisierung', frageText: 'Werden nach Vorfällen oder Trendveränderungen situative Sensibilisierungsmaßnahmen eingeleitet?' },
      { frageId: 'A-03-3-2', abschnitt: '3. Situative Sensibilisierung', frageText: 'Werden LP-relevante Informationen (Neuerungen, Warnhinweise) aktiv an die Belegschaft kommuniziert?' },
    ],
  },
  {
    anlageId: 'A-04',
    name: 'Führungsverhalten und Supervision',
    beschreibung: 'Prüfung der Führungsqualität und Aufsicht als LP-Präventionsfaktor.',
    fragen: [
      { frageId: 'A-04-1-1', abschnitt: '1. Führungsverantwortung', frageText: 'Sind LP-Ziele in die Führungskräfte-Beurteilung und Zielvereinbarungen integriert?' },
      { frageId: 'A-04-1-2', abschnitt: '1. Führungsverantwortung', frageText: 'Kennen Führungskräfte ihre LP-spezifische Verantwortung und Meldepflichten?' },
      { frageId: 'A-04-1-3', abschnitt: '1. Führungsverantwortung', frageText: 'Wird Fehlverhalten von Führungskräften konsequent und ohne Ansehen der Person geahndet?' },
      { frageId: 'A-04-2-1', abschnitt: '2. Tagesaufsicht', frageText: 'Werden Mitarbeiter in risikorelevanten Prozessen aktiv beaufsichtigt?' },
      { frageId: 'A-04-2-2', abschnitt: '2. Tagesaufsicht', frageText: 'Führen Vorgesetzte regelmäßige unangekündigte Kontrollen in Schlüsselprozessen durch?' },
      { frageId: 'A-04-2-3', abschnitt: '2. Tagesaufsicht', frageText: 'Werden Urlaubsabwesenheiten und Vertretungsregelungen LP-seitig berücksichtigt?' },
      { frageId: 'A-04-3-1', abschnitt: '3. Früherkennung', frageText: 'Sind Führungskräfte in der Lage, Warnsignale (Red Flags) von Insidern zu erkennen und zu melden?' },
      { frageId: 'A-04-3-2', abschnitt: '3. Früherkennung', frageText: 'Werden auffällige Verhaltensänderungen (Lebensstil, Arbeitsmuster) systematisch erfasst?' },
    ],
  },
  {
    anlageId: 'A-05',
    name: 'Verhaltensrichtlinien und Compliance',
    beschreibung: 'Bewertung der Wirksamkeit von Verhaltensrichtlinien und deren Einhaltung.',
    fragen: [
      { frageId: 'A-05-1-1', abschnitt: '1. Richtlinienqualität', frageText: 'Gibt es einen aktuellen, schriftlichen Verhaltenskodex mit klaren LP-Bezügen?' },
      { frageId: 'A-05-1-2', abschnitt: '1. Richtlinienqualität', frageText: 'Sind Interessenkonflikte, Nebentätigkeiten und Gefälligkeitsannahmen geregelt?' },
      { frageId: 'A-05-1-3', abschnitt: '1. Richtlinienqualität', frageText: 'Sind Sanktionen bei Verstößen klar definiert und konsequent angewendet?' },
      { frageId: 'A-05-2-1', abschnitt: '2. Kommunikation und Akzeptanz', frageText: 'Kennen alle Mitarbeiter den Verhaltenskodex und haben ihn schriftlich anerkannt?' },
      { frageId: 'A-05-2-2', abschnitt: '2. Kommunikation und Akzeptanz', frageText: 'Wird der Verhaltenskodex regelmäßig kommuniziert (nicht nur bei Einstellung)?' },
      { frageId: 'A-05-3-1', abschnitt: '3. Compliance-Kontrolle', frageText: 'Werden Compliance-Verstöße systematisch erfasst und ausgewertet?' },
      { frageId: 'A-05-3-2', abschnitt: '3. Compliance-Kontrolle', frageText: 'Gibt es ein Verfahren zur Disziplinarmaßnahme, das rechtssicher und konsistent angewandt wird?' },
      { frageId: 'A-05-3-3', abschnitt: '3. Compliance-Kontrolle', frageText: 'Werden Compliance-Kennzahlen der Unternehmensführung regelmäßig berichtet?' },
    ],
  },
  {
    anlageId: 'A-06',
    name: 'Perimeter- und Zonensicherheit',
    beschreibung: 'Prüfung der physischen Sicherheitsinfrastruktur: Außengelände, Zonenkonzept, Zutritt und technische Absicherung.',
    fragen: [
      { frageId: 'A-06-1-1', abschnitt: '1. Perimeter', frageText: 'Ist das Betriebsgelände vollständig und wirkungsvoll eingezäunt oder anderweitig begrenzt?' },
      { frageId: 'A-06-1-2', abschnitt: '1. Perimeter', frageText: 'Sind alle Zugänge (Fahrzeug, Fußgänger, Notausgänge) identifiziert und gesichert?' },
      { frageId: 'A-06-1-3', abschnitt: '1. Perimeter', frageText: 'Ist die Außenbeleuchtung ausreichend und werden Dunkelbereiche regelmäßig überprüft?' },
      { frageId: 'A-06-1-4', abschnitt: '1. Perimeter', frageText: 'Werden Perimetersicherheitsmängel (Lücken, defekte Zäune) unverzüglich behoben?' },
      { frageId: 'A-06-2-1', abschnitt: '2. Zoneneinteilung', frageText: 'Existiert ein dokumentiertes Zonenkonzept (öffentlich / eingeschränkt / gesichert / hochsicher)?' },
      { frageId: 'A-06-2-2', abschnitt: '2. Zoneneinteilung', frageText: 'Sind alle Zonen klar beschildert und sind die Zugangsberechtigung je Zone definiert?' },
      { frageId: 'A-06-2-3', abschnitt: '2. Zoneneinteilung', frageText: 'Werden sensible Bereiche (Serverraum, Tresor, Lager) als hochsichere Zonen geführt?' },
      { frageId: 'A-06-2-4', abschnitt: '2. Zoneneinteilung', frageText: 'Wird das Zonenkonzept nach baulichen oder organisatorischen Änderungen aktualisiert?' },
      { frageId: 'A-06-3-1', abschnitt: '3. Zugang und Kontrolle', frageText: 'Werden alle Personen beim Betreten kontrollierter Zonen identifiziert und registriert?' },
      { frageId: 'A-06-3-2', abschnitt: '3. Zugang und Kontrolle', frageText: 'Werden Besucher und Fremdfirmen beim Betreten empfangen, begleitet und beim Verlassen abgemeldet?' },
      { frageId: 'A-06-3-3', abschnitt: '3. Zugang und Kontrolle', frageText: 'Sind aktive Ausweise von gesperrten oder ausgeschiedenen Mitarbeitern umgehend deaktiviert?' },
      { frageId: 'A-06-3-4', abschnitt: '3. Zugang und Kontrolle', frageText: 'Werden Zutrittsprotokolle regelmäßig auf Auffälligkeiten ausgewertet?' },
      { frageId: 'A-06-4-1', abschnitt: '4. Technische Absicherung', frageText: 'Ist eine funktionsfähige Videoüberwachung an allen sicherheitsrelevanten Punkten installiert?' },
      { frageId: 'A-06-4-2', abschnitt: '4. Technische Absicherung', frageText: 'Werden Videoaufzeichnungen für einen definierten Zeitraum gespeichert und sind sie im Bedarfsfall abrufbar?' },
      { frageId: 'A-06-4-3', abschnitt: '4. Technische Absicherung', frageText: 'Ist ein Einbruchmelde- oder Alarmsystem installiert und wird es regelmäßig gewartet?' },
      { frageId: 'A-06-4-4', abschnitt: '4. Technische Absicherung', frageText: 'Werden technische Sicherheitssysteme regelmäßig auf Funktionsfähigkeit getestet und dokumentiert?' },
    ],
  },
  {
    anlageId: 'A-07',
    name: 'Zugangs- und Berechtigungsmanagement',
    beschreibung: 'Prüfung der Vergabe, Verwaltung und Kontrolle von Zugangsberechtigungen für physische und logische Systeme.',
    fragen: [
      { frageId: 'A-07-1-1', abschnitt: '1. Berechtigungsvergabe', frageText: 'Werden Berechtigungen nach dem Prinzip der minimalen Rechtevergabe (Need-to-know) zugeteilt?' },
      { frageId: 'A-07-1-2', abschnitt: '1. Berechtigungsvergabe', frageText: 'Ist ein formaler Genehmigungsprozess für die Vergabe erhöhter Zugriffsrechte etabliert?' },
      { frageId: 'A-07-1-3', abschnitt: '1. Berechtigungsvergabe', frageText: 'Werden Funktionstrennung und Vier-Augen-Prinzip bei kritischen Transaktionen gewährleistet?' },
      { frageId: 'A-07-2-1', abschnitt: '2. Berechtigungsverwaltung', frageText: 'Werden Berechtigungen bei Stellenwechsel, Kündigung oder Aufgabenänderung unverzüglich angepasst?' },
      { frageId: 'A-07-2-2', abschnitt: '2. Berechtigungsverwaltung', frageText: 'Findet eine regelmäßige Rezertifizierung aller aktiven Berechtigungen statt (mind. halbjährlich)?' },
      { frageId: 'A-07-2-3', abschnitt: '2. Berechtigungsverwaltung', frageText: 'Werden inaktive oder verwaiste Konten systematisch identifiziert und gesperrt?' },
      { frageId: 'A-07-3-1', abschnitt: '3. Monitoring und Kontrolle', frageText: 'Werden Zugriffsaktivitäten auf kritische Systeme protokolliert und regelmäßig ausgewertet?' },
      { frageId: 'A-07-3-2', abschnitt: '3. Monitoring und Kontrolle', frageText: 'Gibt es Alarme bei ungewöhnlichen Zugriffsmustern (außerhalb der Arbeitszeiten, Massenzugriffe)?' },
    ],
  },
  {
    anlageId: 'A-08',
    name: 'Monatliche Standortbewertung',
    beschreibung: 'Regelmäßige Kurzbewertung des Sicherheitsniveaus und LP-Stands am Standort.',
    fragen: [
      { frageId: 'A-08-1-1', abschnitt: '1. Vorfälle und Ereignisse', frageText: 'Wurden im Berichtszeitraum LP-relevante Vorfälle (Diebstahl, Betrug, Regelverstöße) registriert?' },
      { frageId: 'A-08-1-2', abschnitt: '1. Vorfälle und Ereignisse', frageText: 'Wurden alle Vorfälle vollständig dokumentiert und gemäß Eskalationsmatrix gemeldet?' },
      { frageId: 'A-08-1-3', abschnitt: '1. Vorfälle und Ereignisse', frageText: 'Sind Folgemaßnahmen zu offenen Vorfällen aus dem Vormonat abgeschlossen?' },
      { frageId: 'A-08-2-1', abschnitt: '2. Kennzahlen', frageText: 'Sind alle LP-KPIs für den Berichtszeitraum vollständig erhoben und dokumentiert?' },
      { frageId: 'A-08-2-2', abschnitt: '2. Kennzahlen', frageText: 'Liegen die Kennzahlen innerhalb der definierten Toleranzbereiche?' },
      { frageId: 'A-08-3-1', abschnitt: '3. Maßnahmen und Status', frageText: 'Wurden geplante LP-Maßnahmen des Berichtszeitraums umgesetzt?' },
      { frageId: 'A-08-3-2', abschnitt: '3. Maßnahmen und Status', frageText: 'Sind alle offenen Maßnahmen mit klaren Verantwortlichkeiten und Terminen versehen?' },
      { frageId: 'A-08-4-1', abschnitt: '4. Zustand Sicherheitsinfrastruktur', frageText: 'Sind alle sicherheitstechnischen Einrichtungen (Kameras, Schlösser, Alarmanlagen) funktionstüchtig?' },
      { frageId: 'A-08-4-2', abschnitt: '4. Zustand Sicherheitsinfrastruktur', frageText: 'Wurden erkannte Mängel an der Sicherheitsinfrastruktur gemeldet und sind Maßnahmen eingeleitet?' },
    ],
  },
  {
    anlageId: 'A-09',
    name: 'Lager-, Versand- und Inventarsicherheit',
    beschreibung: 'Prüfung der Sicherheitsmaßnahmen im Lager und Versandbereich sowie Inventarkontrollen.',
    fragen: [
      { frageId: 'A-09-1-1', abschnitt: '1. Lagersicherheit', frageText: 'Ist der Lagerbereich klar abgegrenzt und nur berechtigten Personen zugänglich?' },
      { frageId: 'A-09-1-2', abschnitt: '1. Lagersicherheit', frageText: 'Werden Ein- und Auslagerungen vollständig und zeitnah im Warenwirtschaftssystem erfasst?' },
      { frageId: 'A-09-1-3', abschnitt: '1. Lagersicherheit', frageText: 'Werden Hochwertwaren oder leicht entwendbare Artikel besonders gesichert (Käfig, Tresor, separater Raum)?' },
      { frageId: 'A-09-2-1', abschnitt: '2. Wareneingangskontrolle', frageText: 'Werden alle Wareneingänge systematisch auf Menge, Qualität und Lieferschein geprüft?' },
      { frageId: 'A-09-2-2', abschnitt: '2. Wareneingangskontrolle', frageText: 'Sind Wareneingang und Buchhaltung/Bestellung personell getrennt (keine Einzelperson kann komplett kontrollieren)?' },
      { frageId: 'A-09-2-3', abschnitt: '2. Wareneingangskontrolle', frageText: 'Werden Abweichungen zwischen Lieferschein und tatsächlicher Lieferung gemeldet und nachverfolgt?' },
      { frageId: 'A-09-3-1', abschnitt: '3. Inventur und Bestandskontrolle', frageText: 'Finden planmäßige Inventuren in definierten Zyklen statt?' },
      { frageId: 'A-09-3-2', abschnitt: '3. Inventur und Bestandskontrolle', frageText: 'Werden Inventurdifferenzen analysiert, dokumentiert und bei Auffälligkeiten untersucht?' },
      { frageId: 'A-09-3-3', abschnitt: '3. Inventur und Bestandskontrolle', frageText: 'Werden Stichprobeninventuren unangekündigt in risikorelevanten Bereichen durchgeführt?' },
    ],
  },
  {
    anlageId: 'A-10',
    name: 'Kassierprozesse und Transaktionsintegrität',
    beschreibung: 'Bewertung der Kontrollmechanismen rund um Kassenvorgänge und Zahlungsabwicklung.',
    fragen: [
      { frageId: 'A-10-1-1', abschnitt: '1. Kassenprozesse', frageText: 'Sind die Kassenprozesse standardisiert und dokumentiert (Öffnungs-/Schließprozeduren, Kassensturz)?' },
      { frageId: 'A-10-1-2', abschnitt: '1. Kassenprozesse', frageText: 'Führt jeder Kassierer eine eigene, persönliche Kassenschublade oder ein eigenes Konto?' },
      { frageId: 'A-10-1-3', abschnitt: '1. Kassenprozesse', frageText: 'Werden Kassenabweichungen systematisch erfasst, analysiert und auffälligen Mustern nachgegangen?' },
      { frageId: 'A-10-2-1', abschnitt: '2. Transaktionskontrollen', frageText: 'Werden Stornos, Preisnachlässe und Retouren durch Berechtigte autorisiert und protokolliert?' },
      { frageId: 'A-10-2-2', abschnitt: '2. Transaktionskontrollen', frageText: 'Werden Transaktionsmuster (Eigenrabatte, Eigenverkäufe an Mitarbeiter) regelmäßig ausgewertet?' },
      { frageId: 'A-10-2-3', abschnitt: '2. Transaktionskontrollen', frageText: 'Ist der Zugriff auf die POS-Systemkonfiguration auf autorisiertes Personal beschränkt?' },
      { frageId: 'A-10-3-1', abschnitt: '3. Zahlungsabwicklung', frageText: 'Werden Bar- und Kartenzahlungen täglich abgeglichen und Differenzen dokumentiert?' },
      { frageId: 'A-10-3-2', abschnitt: '3. Zahlungsabwicklung', frageText: 'Ist die Geldlogistik (Transport, Zählung, Einzahlung) durch Vier-Augen-Prinzip gesichert?' },
    ],
  },
  {
    anlageId: 'A-11',
    name: 'IT- und Informationssicherheit',
    beschreibung: 'Prüfung der IT-sicherheitsrelevanten Maßnahmen aus LP-Perspektive.',
    fragen: [
      { frageId: 'A-11-1-1', abschnitt: '1. Datenzugriff und -schutz', frageText: 'Ist der Zugriff auf geschäftskritische Daten nach dem Need-to-know-Prinzip beschränkt?' },
      { frageId: 'A-11-1-2', abschnitt: '1. Datenzugriff und -schutz', frageText: 'Werden Datenzugriffsrechte bei Personalveränderungen unmittelbar angepasst?' },
      { frageId: 'A-11-1-3', abschnitt: '1. Datenzugriff und -schutz', frageText: 'Ist der Einsatz von externen Datenträgern (USB, Cloud) geregelt und kontrolliert?' },
      { frageId: 'A-11-2-1', abschnitt: '2. Systemüberwachung', frageText: 'Werden IT-Systemzugriffe protokolliert und ungewöhnliche Aktivitäten automatisch gemeldet?' },
      { frageId: 'A-11-2-2', abschnitt: '2. Systemüberwachung', frageText: 'Werden privilegierte Nutzerkonten (Admin) besonders überwacht?' },
      { frageId: 'A-11-3-1', abschnitt: '3. Endgeräte und mobile Sicherheit', frageText: 'Sind mobile Geräte (Laptops, Smartphones) durch Remote-Wipe geschützt?' },
      { frageId: 'A-11-3-2', abschnitt: '3. Endgeräte und mobile Sicherheit', frageText: 'Wird die Installation nicht genehmigter Software auf Unternehmensgeräten verhindert?' },
    ],
  },
  {
    anlageId: 'A-12',
    name: 'Insider-Risiko-Assessment',
    beschreibung: 'Strukturierte Bewertung des Insider-Risikos im Unternehmen anhand bekannter Indikatoren.',
    fragen: [
      { frageId: 'A-12-1-1', abschnitt: '1. Risikoidentifikation', frageText: 'Sind die für den Standort relevanten Insider-Risikofelder (technisch, organisatorisch, personell) identifiziert?' },
      { frageId: 'A-12-1-2', abschnitt: '1. Risikoidentifikation', frageText: 'Gibt es eine aktuelle Risikobewertung mit Eintrittswahrscheinlichkeit und Schadenpotenzial?' },
      { frageId: 'A-12-1-3', abschnitt: '1. Risikoidentifikation', frageText: 'Werden externe Faktoren (wirtschaftliche Lage, Mitarbeiterstress) in die Risikobewertung einbezogen?' },
      { frageId: 'A-12-2-1', abschnitt: '2. Warnindikatoren', frageText: 'Sind Warnindikatoren (Red Flags) für Insider-Risiken definiert und bekannt (Führung, Sicherheit, HR)?' },
      { frageId: 'A-12-2-2', abschnitt: '2. Warnindikatoren', frageText: 'Werden auffällige Verhaltens- oder Lebensstiländerungen proaktiv erfasst und bewertet?' },
      { frageId: 'A-12-2-3', abschnitt: '2. Warnindikatoren', frageText: 'Gibt es ein klares Eskalationsverfahren beim Auftreten von mehreren Red Flags?' },
      { frageId: 'A-12-3-1', abschnitt: '3. Präventionsmaßnahmen', frageText: 'Sind präventive Maßnahmen für die identifizierten Risikobereiche implementiert?' },
      { frageId: 'A-12-3-2', abschnitt: '3. Präventionsmaßnahmen', frageText: 'Werden die Präventionsmaßnahmen regelmäßig auf Wirksamkeit überprüft?' },
    ],
  },
  {
    anlageId: 'A-13',
    name: 'Lieferanten- und Dienstleistermanagement',
    beschreibung: 'Bewertung der LP-Aspekte im Umgang mit externen Lieferanten und Dienstleistern.',
    fragen: [
      { frageId: 'A-13-1-1', abschnitt: '1. Auswahl und Prüfung', frageText: 'Werden neue Lieferanten und Dienstleister nach LP-relevanten Kriterien geprüft?' },
      { frageId: 'A-13-1-2', abschnitt: '1. Auswahl und Prüfung', frageText: 'Sind LP-Anforderungen (Integrität, Vertragstreue, Nachweispflichten) Bestandteil von Vertragswerken?' },
      { frageId: 'A-13-2-1', abschnitt: '2. Zugang und Begleitung', frageText: 'Werden Fremdfirmen und ihre Mitarbeiter vor Zutritt identifiziert und über Hausregeln informiert?' },
      { frageId: 'A-13-2-2', abschnitt: '2. Zugang und Begleitung', frageText: 'Werden Fremdfirmen in sensiblen Bereichen stets begleitet oder beaufsichtigt?' },
      { frageId: 'A-13-2-3', abschnitt: '2. Zugang und Begleitung', frageText: 'Werden Fremdfirmenpässe/Besucherausweise zeitlich befristet und bei Verlassen zurückgegeben?' },
      { frageId: 'A-13-3-1', abschnitt: '3. Laufende Kontrolle', frageText: 'Werden Vertragserfüllung und LP-Compliance bei laufenden Dienstleistern regelmäßig überprüft?' },
      { frageId: 'A-13-3-2', abschnitt: '3. Laufende Kontrolle', frageText: 'Gibt es ein Verfahren zur schnellen Sperrung des Zugangs bei Sicherheitsvorfällen mit Externen?' },
    ],
  },
  {
    anlageId: 'A-14',
    name: 'Ermittlung und Fallmanagement',
    beschreibung: 'Prüfung der Prozesse für interne Ermittlungen und das Management von LP-Fällen.',
    fragen: [
      { frageId: 'A-14-1-1', abschnitt: '1. Meldung und Aufnahme', frageText: 'Ist ein definierter Prozess für die Meldung und Aufnahme von LP-Verdachtsfällen etabliert?' },
      { frageId: 'A-14-1-2', abschnitt: '1. Meldung und Aufnahme', frageText: 'Werden alle Meldungen (anonym oder namentlich) dokumentiert und einer Erstbewertung unterzogen?' },
      { frageId: 'A-14-2-1', abschnitt: '2. Ermittlungsführung', frageText: 'Werden Ermittlungen von geschultem Personal unter Wahrung der rechtlichen Rahmenbedingungen durchgeführt?' },
      { frageId: 'A-14-2-2', abschnitt: '2. Ermittlungsführung', frageText: 'Ist die Beweissicherung (Sicherung von Daten, Unterlagen, Video) regelgerecht und dokumentiert?' },
      { frageId: 'A-14-2-3', abschnitt: '2. Ermittlungsführung', frageText: 'Werden Betroffene erst nach ausreichender Beweislage und unter Einbeziehung von HR/Rechtsbeistand konfrontiert?' },
      { frageId: 'A-14-3-1', abschnitt: '3. Fallabschluss und Lessons Learned', frageText: 'Werden alle Fälle mit Ergebnis und eingeleiteten Maßnahmen vollständig dokumentiert und abgeschlossen?' },
      { frageId: 'A-14-3-2', abschnitt: '3. Fallabschluss und Lessons Learned', frageText: 'Werden aus abgeschlossenen Fällen Erkenntnisse gewonnen und LP-Prozesse entsprechend angepasst?' },
    ],
  },
  {
    anlageId: 'A-15',
    name: 'Notfall- und Krisenmanagement',
    beschreibung: 'Bewertung der Vorbereitung und Reaktionsfähigkeit auf LP-relevante Notfall- und Krisensituationen.',
    fragen: [
      { frageId: 'A-15-1-1', abschnitt: '1. Planung und Vorbereitung', frageText: 'Gibt es dokumentierte Notfall- und Krisenpläne für LP-relevante Szenarien (Raub, Einbruch, Insidertäter)?' },
      { frageId: 'A-15-1-2', abschnitt: '1. Planung und Vorbereitung', frageText: 'Sind Verantwortlichkeiten und Entscheidungsstrukturen im Krisenfall klar geregelt?' },
      { frageId: 'A-15-1-3', abschnitt: '1. Planung und Vorbereitung', frageText: 'Sind Kontaktdaten (Strafverfolgungsbehörden, externe Spezialisten, Versicherung) aktuell und verfügbar?' },
      { frageId: 'A-15-2-1', abschnitt: '2. Training und Übungen', frageText: 'Werden Mitarbeiter in Notfallverhalten (Raub, Bedrohungslagen) regelmäßig geschult und trainiert?' },
      { frageId: 'A-15-2-2', abschnitt: '2. Training und Übungen', frageText: 'Finden regelmäßige Notfallübungen statt und werden diese ausgewertet?' },
      { frageId: 'A-15-3-1', abschnitt: '3. Nachbereitung', frageText: 'Werden Notfallereignisse vollständig dokumentiert und in die LP-Risikobewertung eingespeist?' },
      { frageId: 'A-15-3-2', abschnitt: '3. Nachbereitung', frageText: 'Erhalten betroffene Mitarbeiter nach kritischen Ereignissen psychologische Unterstützung (PTBS-Vorsorge)?' },
    ],
  },
  {
    anlageId: 'A-16',
    name: 'Betrugsprävention und Schwundkontrolle',
    beschreibung: 'Prüfung der spezifischen Maßnahmen zur Betrugsprävention und Reduzierung von Warenschwund.',
    fragen: [
      { frageId: 'A-16-1-1', abschnitt: '1. Schwundanalyse', frageText: 'Werden Schwunddaten regelmäßig erhoben, nach Ursachen kategorisiert und analysiert?' },
      { frageId: 'A-16-1-2', abschnitt: '1. Schwundanalyse', frageText: 'Werden Hochschwundartikel/-bereiche identifiziert und erhalten priorisierten Schutz?' },
      { frageId: 'A-16-1-3', abschnitt: '1. Schwundanalyse', frageText: 'Werden Trends beim Schwund mit externen Benchmarks und internen Zielen verglichen?' },
      { frageId: 'A-16-2-1', abschnitt: '2. Betrugsprävention', frageText: 'Sind betrugspräventive Kontrollen in Rechnungslegung, Einkauf und Zahlungsverkehr implementiert?' },
      { frageId: 'A-16-2-2', abschnitt: '2. Betrugsprävention', frageText: 'Werden Ausgaben und Verbindlichkeiten durch unabhängige Stellen auf Plausibilität geprüft?' },
      { frageId: 'A-16-2-3', abschnitt: '2. Betrugsprävention', frageText: 'Gibt es ein Verfahren zur Erkennung und Untersuchung von Manipulationen im Buchungssystem?' },
      { frageId: 'A-16-3-1', abschnitt: '3. Technische Schutzmaßnahmen', frageText: 'Werden Warensicherungssysteme (EAS, Sicherheitsetiketten) strategisch und effektiv eingesetzt?' },
      { frageId: 'A-16-3-2', abschnitt: '3. Technische Schutzmaßnahmen', frageText: 'Werden technische Schutzmaßnahmen auf Basis von Schwundanalysen kontinuierlich optimiert?' },
    ],
  },
  {
    anlageId: 'A-17',
    name: 'Compliance und Rechtskonformität',
    beschreibung: 'Bewertung der Einhaltung rechtlicher und regulatorischer Anforderungen im LP-Bereich.',
    fragen: [
      { frageId: 'A-17-1-1', abschnitt: '1. Rechtliche Grundlagen', frageText: 'Sind die relevanten gesetzlichen Anforderungen (Arbeitsrecht, Datenschutz, Strafrecht) für LP-Maßnahmen bekannt und berücksichtigt?' },
      { frageId: 'A-17-1-2', abschnitt: '1. Rechtliche Grundlagen', frageText: 'Werden Änderungen in der relevanten Rechtslage zeitnah identifiziert und LP-Prozesse entsprechend angepasst?' },
      { frageId: 'A-17-2-1', abschnitt: '2. Datenschutz im LP-Bereich', frageText: 'Werden Videoüberwachung, Zutrittsdaten und Ermittlungsunterlagen DSGVO-konform erhoben und verarbeitet?' },
      { frageId: 'A-17-2-2', abschnitt: '2. Datenschutz im LP-Bereich', frageText: 'Sind Betriebs-/Mitarbeitervertretungen über Kontrollmaßnahmen informiert und ggf. zugestimmt?' },
      { frageId: 'A-17-2-3', abschnitt: '2. Datenschutz im LP-Bereich', frageText: 'Werden Löschfristen für LP-relevante Daten und Aufzeichnungen eingehalten?' },
      { frageId: 'A-17-3-1', abschnitt: '3. Dokumentation und Nachweisführung', frageText: 'Werden alle LP-Maßnahmen und -Entscheidungen in einer Weise dokumentiert, die einer rechtlichen Prüfung standhält?' },
      { frageId: 'A-17-3-2', abschnitt: '3. Dokumentation und Nachweisführung', frageText: 'Gibt es einen strukturierten Prozess für die Übergabe von Fällen an Strafverfolgungsbehörden?' },
    ],
  },
  {
    anlageId: 'A-18',
    name: 'Gesamtreview und Jahresbewertung',
    beschreibung: 'Umfassende jährliche Gesamtbewertung des Loss Prevention Management Systems.',
    fragen: [
      { frageId: 'A-18-1-1', abschnitt: '1. Jahresrückblick', frageText: 'Wurden alle für das Jahr geplanten LP-Projekte und -Maßnahmen realisiert?' },
      { frageId: 'A-18-1-2', abschnitt: '1. Jahresrückblick', frageText: 'Haben die umgesetzten Maßnahmen die erwarteten LP-Effekte (Schwundreduzierung, Vorfallrückgang) erzielt?' },
      { frageId: 'A-18-1-3', abschnitt: '1. Jahresrückblick', frageText: 'Wurden alle LP-relevanten Audits und Überprüfungen (A-01 bis A-17) im Jahresverlauf durchgeführt?' },
      { frageId: 'A-18-2-1', abschnitt: '2. Zielerreichung', frageText: 'Wurden die LP-Jahresziele (KPIs) erreicht und wurden Abweichungen analysiert?' },
      { frageId: 'A-18-2-2', abschnitt: '2. Zielerreichung', frageText: 'Wurde der LP-Jahresbericht der Unternehmensführung vorgelegt und besprochen?' },
      { frageId: 'A-18-3-1', abschnitt: '3. Stärken und Verbesserungspotenziale', frageText: 'Wurden die größten Stärken des LP-Systems identifiziert und für das Folgejahr gesichert?' },
      { frageId: 'A-18-3-2', abschnitt: '3. Stärken und Verbesserungspotenziale', frageText: 'Wurden die wesentlichen Verbesserungspotenziale identifiziert und in den Jahresplan eingearbeitet?' },
      { frageId: 'A-18-4-1', abschnitt: '4. Planung Folgejahr', frageText: 'Ist ein LP-Plan für das Folgejahr (Projekte, Budgets, Ziele) von der Führung genehmigt?' },
      { frageId: 'A-18-4-2', abschnitt: '4. Planung Folgejahr', frageText: 'Wurden Erkenntnisse aus abgeschlossenen Fällen und Audits in die Planung des Folgejahres einbezogen?' },
    ],
  },
];

export function getAnlage(anlageId: string): ChecklisteAnlage | undefined {
  return CHECKLISTEN_KATALOG.find((a) => a.anlageId === anlageId);
}

export function getAnlagenMeta(): ChecklisteAnlageMeta[] {
  return CHECKLISTEN_KATALOG.map((a) => ({
    anlageId: a.anlageId,
    name: a.name,
    beschreibung: a.beschreibung,
    anzahlFragen: a.fragen.length,
  }));
}
